CertificateRevokedException: test getAuthorityName
Test to make sure CertificateRevokedException behaves correctly for
getAuthorityName().

(cherry picked from commit 53102cac4dfa10baf3e0735054a2839c25c6e11c)

Bug: 27812109
Change-Id: I3d9724e636b895b9359a0fd37e8bc0cc89dcc756