Exercising our XPath implementation with 279 of Jaxen's tests.
Both our implementation and the RIv6 fail 29 tests, 17 of which are
"could not find function" failures regarding our common lack of
support for the evaluate(), document(), upper-case() and lower-case()
functions.

In addition, our implementation fails 10 additional tests:
  xml/moreover.xml / /child::node() "expected:<1> but was:<3>"
  xml/simple.xml / string() "expected:<abd> but was:<"
  xml/web.xml / /child::node() "expected:<web-app> but was:<>"
  xml/web.xml / child::node() "expected:<web-app> but was:<>"
  xml/web.xml / name(/child::node()) "expected:<web-app> but was:<>"
  xml/web.xml / name(/child::node()) "expected:<web-app> but was:<>"
  xml/web.xml / name(/node()) "expected:<web-app> but was:<>"
  xml/web.xml / name(child::node()) "expected:<web-app> but was:<>"
  xml/web.xml / name(node()) "expected:<web-app> but was:<>"
  xml/web.xml /* name(../child::node()) "expected:<web-app> but was:<>"

Change-Id: Icb4695bbf826fd8f1c1ffae5e857169ff551f75e