Revert "Implement Libcore.os.listxattr"
Bug: 31175927

Fails with:
  libcore.io.OsTest#test_xattr_Errno
    junit.framework.AssertionFailedError: expected:<0> but was:<1>
    	at junit.framework.Assert.assertEquals(Assert.java:205)
    	at libcore.io.OsTest.test_xattr_Errno(OsTest.java:640)
  libcore.io.OsTest#test_xattr_Errno FAIL (EXEC_FAILED)

This reverts commit 2e408060cfa6ac19d44d7cddfe2a9f7c28ecbe85.

Change-Id: I273f690ee9bc3c536f6486c74470dcb4e784c335