Let ProcessBuilderTest.testRedirectInherit() run sleep rather than sh
It appears that /system/bin/sh exits quickly with code 0 when inheriting
all file descriptors from the test process (presumably it doesn't like
something about them, e.g. perhaps stdin is /dev/null). This caused
ProcessBuilderTest.testRedirectInherit() to fail in ~ 0.5% of runs with
ErrnoException: stat failed: ENOENT (No such file or directory)
while stat-ing /proc/[childPDI]/fd/0 and friends.

"sleep 5" is less picky about its file descriptors; therefore this
CL changes the test to use that command.

Bug: 27464570
Test: Ran ProcessBuilderTest.testRedirectInherit() 40000 times in a
      loop (took about a minute on a Nexus 6P).

Change-Id: I8bde31a7b9b674b98822d4229922968bbc862b86