ConcurrentModificationException: Add test coverage for message, cause.
Adding such coverage for other exceptions is left to follow-up CLs.

Test: atest CtsLibcoreTestCases:org.apache.harmony.tests.java.util.ConcurrentModificationExceptionTest
Change-Id: I5c02571c63d5a2203b4aa0a49e4348304e40eca2