misc: Tweak Android change documentation, revert redundant changes.
Tweaked existing or added missing Android change documentation
for misc ojluni .java files.

Also got rid of a couple of small needless differences
(e.g. indentation) vs. upstream OpenJDK8u121-b13.

The selection of files touched by this CL is fairly arbitrary.
Future CLs will likely apply similar changes to other files.

AbstractStringBuilder: Revert minor indentation difference vs. upstream
ArrayIndexOutOfBoundsException: Tweak docs for @hide constructors
Byte: Tweak change docs
Console: Minor tweaks to minimize diff, minor improvements to change docs
DeleteOnExitHook: add missing Android-changed documentation
InterruptedIOException: Added change comment body.
HijrahChronology: Revert minor indentation difference vs. upstream
SocketTimeoutException: Added change comment body.
Serializable:: add missing Android-added documentation.
SerializablePermission: Improve toplevel documentation, added Android-changed comment

Bug: 35910877
Test: Treehugger build succeeds
Change-Id: Ia7d1236fb694fc706ae1bba7ba31b320b00a2795