Libcore: Add a private constructor to NoClassDefFoundError
Add a private constructor that accepts a Throwable cause. Add a test
to ensure availability of the constructor.

Bug: 25445103
Change-Id: I6a0dc54e78312283faf23415887eff387531407f