Try to reduce old SSLSocketTest flakiness by closing SSLSocket
Device testing reported test_creationStressTest failing due to:

    java.net.SocketException: socket failed: EMFILE (Too many open files)

Made a quick pass over this to close sockets to prevent this.

Change-Id: Ieffd3c04839e04f78abb3b6d2a2e96b3ccb20e67