Revert "Add change comments in DecimalFormat/NumberFormat."
This reverts commit f8dc36d04961d13ec0b0d2692fba6ca2dbd0a184.

Reason for revert: Breaks libcore tests:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.icu.text.DecimalFormat.applyPattern(java.lang.String)' on a null object reference
    	at java.text.DecimalFormat.applyPattern(DecimalFormat.java:1289)
    	at java.text.DecimalFormat.readObject(DecimalFormat.java:1712)

Bug: 65669355
Change-Id: Ia3d82f4835fa7382533982e8edd73aa031a90860
Test: none